"""Render docs/residency.md's sub-processor table from the residency allow-list object (ADR-0008,
spec A4 / #94, #112) -- the table is generated, not hand-maintained, so the doc cannot silently
drift from `config/residency.toml`: the two used to be checked against each other by a set of
hand-written per-residency assertions in `tests/test_doc_claims.py`; that test now compares this
script's rendering with the marked section of the doc directly (data, not prose).

    uv run python scripts/render_residency_table.py           # rewrite docs/residency.md in place
    uv run python scripts/render_residency_table.py --check   # exit 1 if the doc is stale, no write

Follows `scripts/render_architecture.py`'s conventions: a pure `render_*` function the tests
import directly, and a thin `main()` that does the one bit of I/O (reading/writing the doc).
"""

from __future__ import annotations

import sys
from pathlib import Path

from app.residency import ResidencyAllowList

DOC_PATH = Path(__file__).resolve().parent.parent / "docs" / "residency.md"

# The doc's own markers (see docs/residency.md): everything between them is this script's output,
# never hand-edited. `extract_section`/`updated_doc` below split on these exact strings.
START_MARKER = (
    "<!-- residency-table:start (generated by scripts/render_residency_table.py -- "
    "do not edit by hand) -->"
)
END_MARKER = "<!-- residency-table:end -->"

_TABLE_HEADER = (
    "| Residency | Gateway host patterns | Embedding endpoint | Trace sink host | "
    "Model aliases |\n|---|---|---|---|---|"
)


def render_table(allow_list: ResidencyAllowList) -> str:
    """The Markdown table body -- header plus one row per residency, no surrounding markers."""
    rows = [_TABLE_HEADER]
    for residency in allow_list.residencies:
        route = allow_list.route_for(residency)
        patterns = ", ".join(f"`{p}`" for p in route.model_host_patterns)
        aliases = ", ".join(f"`{a}`" for a in allow_list.model_aliases(residency)) or "—"
        rows.append(
            f"| `{residency}` | {patterns} | `{route.embedding_endpoint}` | "
            f"`{route.trace_sink_host}` | {aliases} |"
        )
    return "\n".join(rows)


def render_section(allow_list: ResidencyAllowList) -> str:
    """The table wrapped in its start/end markers, exactly as it appears in docs/residency.md."""
    return f"{START_MARKER}\n{render_table(allow_list)}\n{END_MARKER}"


def extract_section(doc_text: str) -> str:
    """The marked section (markers included) as it currently reads in `doc_text`."""
    _, rest = doc_text.split(START_MARKER, 1)
    body, _ = rest.split(END_MARKER, 1)
    return f"{START_MARKER}{body}{END_MARKER}"


def updated_doc(doc_text: str, allow_list: ResidencyAllowList) -> str:
    """`doc_text` with its marked section replaced by a fresh rendering."""
    before, rest = doc_text.split(START_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    return f"{before}{render_section(allow_list)}{after}"


def main(argv: list[str]) -> int:
    allow_list = ResidencyAllowList.load()
    doc_text = DOC_PATH.read_text(encoding="utf-8")
    updated = updated_doc(doc_text, allow_list)
    if "--check" in argv:
        if updated != doc_text:
            print(f"{DOC_PATH} is stale -- run this script with no flags to regenerate it.")
            return 1
        print(f"{DOC_PATH} matches the residency allow-list.")
        return 0
    DOC_PATH.write_text(updated, encoding="utf-8")
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
